control_move:
  ros__parameters:
    cmd_vel_topic: /cmd_vel
    wheel_velocity_topic_prefix: /m_vel

    wheel_radius: 0.0625
    track_width: 0.42

    max_linear_velocity: 1.0
    max_wheel_velocity: 4.8
    min_wheel_velocity: 1.0
    wheel_deadband: 0.2

    publish_period: 0.05
    cmd_vel_timeout: 0.25

radiolink_control:
  ros__parameters:
    joy_topic: joy
    cmd_vel_topic: /cmd_vel

    publish_period: 0.05
    joystick_timeout: 0.5

    slow_speed: 0.2
    normal_speed: 0.5
    fast_speed: 1.0
    rotation_scale: 2.5

    linear_axis: 1
    angular_axis: 3
    speed_axis: 6
    safety_axis_left: 2
    safety_axis_right: 4
    safety_threshold: 0.8

odom:
  ros__parameters:
    imu_topic: /bhi360/imu
    odom_topic: /odom_pose2d
    wheel_odom_topic_prefix: /m_odom
    wheel_radius: 0.0625
    publish_period: 0.02
    max_dt: 0.2

bat_monitor:
  ros__parameters:
    battery_topic: /bat
    led_service: /hmi/led
    voltage_threshold: 13.8
    blink_period: 0.25
    led_interface: 0

imu:
  ros__parameters:
    freq: 500.0
    imu_topic: /bhi360/imu
    frame_id: imu_link
    reconnect_period: 1.0